#ifndef STATUS_H
#define STATUS_H

#define STATUS_OK 0
#define STATUS_IO_ERROR 1
#define STATUS_INVALID_ARG 2
#define STATUS_NOT_ENOUGH_MEM 3
#define STATUS_GENERIC_ERROR 4
#define STATUS_BAD_FILE_PATH 5
#define STATUS_NOT_IMPLEMENTED 6

#define STATUS_OUT_OF_PROCS 7

#define STATUS_VPN_NOT_PRESENT 8

#define STATUS_INVALID_USER_MEM_ACCESS 9

#define STATUS_INVALID_EXEC_FORMAT 10

#define STATUS_INVALID_MEMORY_REGION 11

#define STATUS_OUT_OF_VMEM_BLOCKS 12

#define SYSCALL_NOT_IMPLEMENTED 13

#define STATUS_PROC_NOT_ZOMBIE 14

#define STATUS_PROC_EXCEPTION 15

#define MAGIC_ERROR 19891213
#endif
