#ifndef STATUS_H
#define STATUS_H

#define STATUS_OK 0
#define STATUS_IO_ERROR 1
#define STATUS_INVALID_ARG 2
#define STATUS_NOT_ENOUGH_MEM 3
#define STATUS_GENERIC_ERROR 4
#define STATUS_BAD_FILE_PATH 5
#define STATUS_NOT_IMPLEMENTED 6

#define MAGIC_ERROR 19891213
#endif
