name: clang-tidy-lint

on: [push, pull_request]

jobs:
  clang_tidy_lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/setup-nasm@v1

    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest
        platform: x64

    - name: Install bear
      run: |
        sudo apt-get update
        sudo apt-get -y install bear

    - name: Install homebrew
      run: |
        sudo apt-get install build-essential procps curl file git
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
        test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
        echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile
        echo "::add-path::/home/linuxbrew/.linuxbrew/bin"
        brew --version

    - name: Verify Homebrew's Installation
      run: brew --version

    - name: Install i686 tools
      run: |
        brew install i686-elf-binutils i686-elf-gcc
    
    - name: Lint
      run: |
        make lint